[General]
skip-proxy = 127.0.0.1, localhost, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
allow-wifi-access = false
ipv6 = false

[Rule]
RULE-SET,https://raw.githubusercontent.com/qianye9998/loon_rules/main/rules/00_custom_proxy.list,Proxy
RULE-SET,https://raw.githubusercontent.com/qianye9998/loon_rules/main/rules/01_custom_direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/qianye9998/loon_rules/main/rules/02_custom_reject.list,REJECT
RULE-SET,https://raw.githubusercontent.com/qianye9998/loon_rules/main/rules/10_domestic_direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/qianye9998/loon_rules/main/rules/20_global_proxy.list,Proxy
RULE-SET,https://raw.githubusercontent.com/qianye9998/loon_rules/main/rules/21_adblock_reject.list,REJECT
RULE-SET,https://raw.githubusercontent.com/qianye9998/loon_rules/main/rules/30_streaming_proxy.list,Streaming
RULE-SET,https://raw.githubusercontent.com/qianye9998/loon_rules/main/rules/40_ai_proxy.list,AI
FINAL,Proxy
